[build]
  # Commande de build pour Next.js
  command = "npm run build"
  # Dossier de sortie pour le static export
  publish = "out"
  # Timeout de build augmenté pour Next.js
  timeout = 600

[build.environment]
  # Variables d'environnement pour le build
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_TELEMETRY_DISABLED = "1"
  # Configuration pour le static export
  NEXT_OUTPUT = "export"

# Redirections pour les routes API (vers des fonctions serverless si nécessaire)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirections pour le routing Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers pour la sécurité et la performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Headers pour les assets statiques
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuration des fonctions serverless (si nécessaire pour les API)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Plugin pour Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"